package constants;

public enum GroupEnum {
    CIVIL_ENGINEERING_GROUP_1,
    CIVIL_ENGINEERING_GROUP_2,
    ARCHITECTURE_GROUP_1,
    ARCHITECTURE_GROUP_2,
    INSTRUMENT_MAKING_GROUP_1,
    INSTRUMENT_MAKING_GROUP_2,
    ENERGY_GROUP_1,
    ENERGY_GROUP_2,
    ECONOMIC_GROUP_1,
    ECONOMIC_GROUP_2,
}
